# # vars file for vm_creation

# number_of_sandboxes: 2               # Number of sandboxes to create
# base_rg_name: "M-sandbox-rg"
# Location : West Europe


# # Resource_group_name : M-Testing_environment
# # Location : West Europe
# vnet_name : sandbox_vnet
# address_prefixes_vnet : 10.0.0.0/16
# subnet : sandbox_subnet
# address_prefixes_subnet : 10.0.1.0/24
# vm_name : Sandbox-vm 
# vm_size : Standard_B1s
# admin_username : azureuser
# Ip_name : PublicIP-Sandbox
# NIC_name : NIC-sandbox
# ssh_public_key : 2HBzlIidEILJDMorAXpePkbtqB+KwoIVUZVeaejge4Y
# storage : sandboxstorage78
# nsg : nsg-sandbox


vars:
    idx: "{{ item }}"
    item_dict:
      name: "{{ base_rg_name }}-{{ idx }}"
      location: "{{ location }}"
      vnet_name: "sandbox-vnet-{{ idx }}"
      subnet: "subnet{{ idx }}"
      address_prefixes_vnet: "10.{{ (idx | int - 1) | string }}.0.0/16"
      address_prefixes_subnet: "10.{{ (idx | int - 1) | string }}.0.0/24"
      NIC_name: "nic{{ idx }}"
      Ip_name: "ip{{ idx }}"
      vm_name: "vm{{ idx }}"
      vm_size: "Standard_B1s"
      admin_username: "azureuser"
      storage: "stg{{ idx }}"