galaxy_info:
  author: Jane Doe
  description: Role to provision sandbox environments in Azure
  company: ACME Inc.
  license: MIT
  min_ansible_version: "2.1"

  # platforms your role supports
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Windows
      versions:
        - all

  galaxy_tags: []
  # List tags for your role here, one per line. Each tag must be a single word.
  # Example:
  # - azure
  # - sandbox

dependencies: []
# List role dependencies here, one per line. Example:
# - geerlingguy.git

